name: Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Deploy Docker Image
    runs-on: ubuntu-22.04
    steps:
      - name: Retrieve source code
        uses: actions/checkout@v3

      - name: Build and push
        uses: openzim/docker-publish-action@v9
        with:
          image-name: openzim/wp1_selection_tools
          registries: ghcr.io
          on-master: latest
          restrict-to: openzim/wp1_selection_tools
          credentials: |
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
